/**
 * @author Toru Nagashima
 * @copyright 2017 Toru Nagashima. All rights reserved.
 * See LICENSE file in root directory for full license.
 */
"use strict"

module.exports = {
    "extends": ["./browser.js", "./modules.js"],
    "globals": { "process": false },
    "parser": "vue-eslint-parser",
    "parserOptions": {
        "ecmaFeatures": { "jsx": true },
        "ecmaVersion": 2017,
    },
    "rules": {
        "no-process-env": "off",
        "vue/attribute-hyphenation": "error",
        "vue/html-end-tags": "error",
        "vue/html-quotes": "error",
        "vue/html-self-closing": "error",
        "vue/jsx-uses-vars": "error",
        "vue/max-attributes-per-line": "error",
        "vue/mustache-interpolation-spacing": "error",
        "vue/name-property-casing": "error",
        "vue/no-async-in-computed-properties": "error",
        "vue/no-confusing-v-for-v-if": "error",
        "vue/no-dupe-keys": "error",
        "vue/no-duplicate-attributes": "error",
        "vue/no-multi-spaces": "error",
        "vue/no-parsing-error": ["error", {
            "abrupt-closing-of-empty-comment": true,
            "absence-of-digits-in-numeric-character-reference": true,
            "cdata-in-html-content": true,
            "character-reference-outside-unicode-range": true,
            "control-character-in-input-stream": true,
            "control-character-reference": true,
            "duplicate-attribute": true,
            "end-tag-with-attributes": true,
            "end-tag-with-trailing-solidus": true,
            "eof-before-tag-name": true,
            "eof-in-cdata": true,
            "eof-in-comment": true,
            "eof-in-tag": true,
            "incorrectly-closed-comment": true,
            "incorrectly-opened-comment": true,
            "invalid-first-character-of-tag-name": true,
            "missing-attribute-value": true,
            "missing-end-tag-name": true,
            "missing-semicolon-after-character-reference": true,
            "missing-whitespace-between-attributes": true,
            "nested-comment": true,
            "non-void-html-element-start-tag-with-trailing-solidus": false,
            "noncharacter-character-reference": true,
            "noncharacter-in-input-stream": true,
            "null-character-reference": true,
            "surrogate-character-reference": true,
            "surrogate-in-input-stream": true,
            "unexpected-character-in-attribute-name": true,
            "unexpected-character-in-unquoted-attribute-value": true,
            "unexpected-equals-sign-before-attribute-name": true,
            "unexpected-null-character": true,
            "unexpected-question-mark-instead-of-tag-name": true,
            "unexpected-solidus-in-tag": true,
            "unknown-named-character-reference": true,
            "x-invalid-end-tag": true,
            "x-invalid-namespace": true,
        }],
        "vue/no-reserved-keys": "error",
        "vue/no-shared-component-data": "error",
        "vue/no-side-effects-in-computed-properties": "error",
        "vue/no-template-key": "error",
        "vue/no-textarea-mustache": "error",
        "vue/order-in-components": "error",
        "vue/require-component-is": "error",
        "vue/require-default-prop": "error",
        "vue/require-prop-types": "error",
        "vue/require-render-return": "error",
        "vue/require-v-for-key": "error",
        "vue/require-valid-default-prop": "error",
        "vue/return-in-computed-property": "error",
        "vue/this-in-template": "error",
        "vue/v-bind-style": "error",
        "vue/v-on-style": "error",
        "vue/valid-template-root": "error",
        "vue/valid-v-bind": "error",
        "vue/valid-v-cloak": "error",
        "vue/valid-v-else": "error",
        "vue/valid-v-else-if": "error",
        "vue/valid-v-for": "error",
        "vue/valid-v-html": "error",
        "vue/valid-v-if": "error",
        "vue/valid-v-model": "error",
        "vue/valid-v-on": "error",
        "vue/valid-v-once": "error",
        "vue/valid-v-pre": "error",
        "vue/valid-v-show": "error",
        "vue/valid-v-text": "error",
    },
    "settings": {
        "node": {
            "tryExtensions": [".js", ".json", ".vue"],
        },
    },
}
